config/routes.rb
Wanderdesk::Application.routes.draw do

  resources :offices
  match 'offices/find' => 'offices#find'
  resources :users
  resources :deals do
    resources :messages
  end
  resource :session
  resources :favorites, only: [:create, :index]
  resources :availabilities
  resources :features
  resources :featurings
  resources :tags

  root to: "offices#index"

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :addr1, :addr2, :arrangement, :available, :city, :state, :description, :occupancy, :owner_id, :price, :size, :title, :zip, :longitude, :latitude

  validates :title, :longitude, :price, :arrangement, :occupancy, presence: true
  validates :price, numericality: { greater_than: 0, less_than: 100000}
  validates :occupancy, numericality: { greater_than: 0, less_than: 200}

  geocoded_by :address

  reverse_geocoded_by :latitude, :longitude do |o, res|
    if res = res.first
      o.state = res.state if o.state == nil || o.state != o.state
      o.zip = res.zipcode if o.zip == nil
      o.city = res.city if o.city == nil || o.city != res.city
    end
  end

  before_validation :geocode
  before_create :reverse_geocode

  before_update :geocode

  belongs_to(:owner,
  class_name: "User",
  foreign_key: :owner_id,
  primary_key: :id
  )

  has_many(:favoritings,
  class_name: "Favorite",
  foreign_key: :office_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(:availabilities,
  class_name: "Availability",
  foreign_key: :office_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(:featurings,
  class_name: "Featuring",
  foreign_key: :office_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(:features, through: :featurings, source: :feature )

  has_many(:photos,
  class_name: "Photo",
  foreign_key: :office_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(:deals,
  class_name: "Deal",
  foreign_key: :office_id,
  primary_key: :id,
  dependent: :destroy
  )


  def address
    [self.addr1, self.city, self.state, self.zip].compact.keep_if{|e| e != ""}.join(", ")
  end
  #
  # def hard_geocode
  #   addr = address.keep_if {|el| el != ""}
  #   while addr.length > 0
  #     geoaddr = addr.join(", ")
  #     Office.geocoded_by geoaddr.to_sym
  #     status = self.geocode
  #     return status if status != nil
  #     addr = addr[1..-1]
  #   end
  #   return nil
  # end
  #
  def free?(start, finish)

  end


end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  include OfficesHelper
  skip_before_filter :check_logged_in, only: [:index,:show, :find]

  before_filter :has_access, only: [:edit, :destroy, :update]


  def index
    @offices =  (current_user && current_user.geocoded?) ? Office.near([current_user.latitude, current_user.longitude], 36000).last(10) : Office.last(10)
    @features = Feature.all
    @current_features = params[:search_params] == nil ? [] : params[:search_params][:features]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  def find

    @features = Feature.all
    @current_features = params[:search_params][:features] == nil ? [] : params[:search_params][:features][1..-1].map{|f| f.to_i}
    # fail
    search_params = []

    # To seriously refactor!

    if params[:search_params]

      locator = current_user || request.location
      radius = (params[:acceptable_range] if params[:acceptable_range] != '') || 20


      to_search = ["SELECT * FROM offices"]
      if params[:search_params][:city] != ""
        locator = params[:search_params][:city]
      end

      if params[:search_params][:price] != ""
        price = params[:search_params][:price]
        search_params << "price < #{price}"
      end
      if params[:search_params][:features] != [nil]

        query = build_ridiculous_query((params[:search_params][:features])[1..-1])

        search_params = search_params.join(" AND ")
        to_search = ["SELECT * FROM (#{query}) "]+(params[:search_params][:features])[1..-1]
        to_search[0] += " WHERE #{search_params} " if !search_params.empty?

      elsif !search_params.empty?
        # fail
      search_params = search_params.flatten.join(" AND ") if search_params.is_a? Array
      to_search[0] = ("(SELECT * FROM \"offices\" as main WHERE "+ search_params.to_s + ")")

      end
    end


    # fail
    # Need to refactor the keep_if below to be a proper SQL query
    if params[:search_params][:features] != [nil]
      to_search[0] = Office.near(locator, radius).to_sql.gsub("FROM \"offices\"", "FROM (" + to_search[0]+" as otheroffices) as offices")
      @offices = Office.find_by_sql(to_search)
    else
      to_search[0] = ((search_params.is_a? Array) ? search_params.join(" AND ").to_s : search_params)

      @offices = Office.where(to_search).near(locator, radius)
    end

    # @offices = Office.find_by_sql(to_search)
    # fail

              #.order("created_at DESC")
    # @offices.keep_if{|o| (o.features.map{|f| f.id}. & @current_features) == @current_features }
    @current_features.map!{|f| f.to_s}
    # fail
    respond_to do |format|
      format.html { render "offices#index" => @offices}
      format.json { render json: @offices }
    end
  end

  def show
    @office = Office.find(params[:id])
    @availabilities = @office.availabilities
    @features = @office.features
    @photos = @office.photos[0]

    p @availabilities

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  def new
    @office = Office.new
    @availabilities = [Availability.new]
    @features = Feature.all
    @current_features = []
    respond_to do |format|
      format.html
      format.json { render json: @office }
    end
  end

  def edit
    @office = Office.find(params[:id])
    @availabilities = @office.availabilities + [Availability.new]
    @features = Feature.all
    @current_features = @office.features.map{|f| f.id}
  end

  def create
    begin
      ActiveRecord::Base.transaction do

        @availabilities = []
        @office = Office.new(params[:office])
        @office.owner_id = current_user.id
        @availabilities = params[:availabilities].map{|_, av_params| Availability.new(av_params)} || []

        @feats = (params[:features])[1..-1].map{|f| Feature.find(f)} # First value always blank?
        @office.save
        if params[:photos]
          @office.photos = [Photo.create({picture: params[:photos][:picture], office_id: @office.id})]
        end
        @office.features = @feats

        current_feats = @office.featurings

        @availabilities.keep_if{|a| !a.start_date.nil? && !a.end_date.nil? }
        @availabilities.each {|av| av.office = @office; av.save}


        raise "invalid" unless @office.valid? && @availabilities.all? {|a| a.valid?}

      end
    rescue StandardError => e
      puts "-------------"
      p e.message
      puts "-------------"
      # flash[:errors] = @office.errors.full_messages + @availabilities.map(&:errors).flatten
      @features = Feature.all
      @current_features = []
      render :new
    else
      redirect_to root_url
    end

    # Maybe revive for backbone
    # respond_to do |format|
    #   if @office.save
    #     format.html { redirect_to @office, notice: 'Office was successfully created.' }
    #     format.json { render json: @office, status: :created, location: @office }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @office.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    begin
      ActiveRecord::Base.transaction do
        @office = Office.find(params[:id])
        @office.update_attributes(params[:office])

        @feats = (params[:features])[1..-1].map{|f| Feature.find(f)} # First value always blank?
        @office.features = @feats
        photo = [Photo.create({picture: params[:photos][:picture], office_id: @office.id})] if params[:photos]
        @office.photos = photo if photo


        @availabilities = params[:availabilities].map do |_, av_params|
          if av_params[:id]
            av = Availability.find(av_params[:id])
            av_params[:id] = ""
            if av_params.all?{|x, y| y == ""}
              av.destroy
              next nil
            end
            av.update_attributes(av_params)
            av
          else
            Availability.new(av_params)
          end
        end.compact
      @availabilities.keep_if {|x| x.attributes != Availability.new.attributes }

      @availabilities.each {|av| av.office_id = params[:id]; av.save}

      raise "invalid" unless @office.valid? && @availabilities.all? {|a| a.valid?}
      end
    # rescue
    #   flash[:errors] = @office.errors.full_messages + @availabilities.map(&:errors).flatten
    #   render :new
    else
      redirect_to root_url
    end
  end

  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end

  private

  def has_access
    redirect_to root_url if Office.find(params[:id]).owner_id != current_user.id
  end

end

app/helpers/offices_helper.rb
module OfficesHelper
  def build_ridiculous_query(features)
    rec_query(features.length) + " WHERE feature_id=?"
  end

  def rec_query(i)
    if i <= 1
      "SELECT DISTINCT offices.* FROM offices JOIN featurings ON featurings.office_id = offices.id"
    else
      expo = rec_query(i-1)
      expo + " JOIN (SELECT DISTINCT offices.* FROM offices JOIN featurings ON featurings.office_id = offices.id WHERE feature_id=?) as o#{i} ON offices.id = o#{i}.id"
    end
  end

  def deal_open?(office_id)
    return true if Deal.find_by_office_id_and_owner_id(office_id, current_user.id)
    return true if Deal.find_by_office_id_and_renter_id(office_id, current_user.id)
    false
  end


end

# "SELECT DISTINCT offices.* FROM offices JOIN featurings ON featurings.office_id = offices.id JOIN (SELECT DISTINCT offices.* FROM offices
# JOIN featurings ON featurings.office_id = offices.id WHERE feature_id=?) as o2 ON offices.id = o2.id JOIN (SELECT DISTINCT offices.* FROM offices
# JOIN featurings ON featurings.office_id = offices.id WHERE feature_id=?) as o3 ON offices.id = o3.id WHERE feature_id=?"

app/views/offices/_filter.html.erb
<!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script> -->

 <div id="map-canvas"></div>


<form action="<%= offices_find_url %>" method="post">
  <%= auth %>

  <input type="submit" value="Filter" class="filter-button">

  <div class="form-item">
    <label for="city-input"> Location or City
        <input type="text" id="city-input" name="search_params[city]" value="<%= params[:search_params][:city] if params[:search_params] %>">
  </div>

  <div class="form-item">
    <label>Max Price
      <input type="integer" name="search_params[price]" value="<%= params[:search_params][:price] if params[:search_params] && params[:search_params][:price] %>">
    </label>

  </div>

  <div class="form-item">
    <label>Spaces Needed
      <input type="integer" class="small-field" maxlength="3" name="search_params[occupancy]" <%= "value=#{params[:search_params][:occupancy]}" if params[:search_params] %>>
    </label>
  </div>

  <div class="form-item">
    <label>Distance (mi)
      <input type="integer" name="acceptable_range" value="<%= params[:acceptable_range] if params[:acceptable_range]%>" %>
    </label>
  </div>

  <label>Features
    <input type="hidden" name="search_params[features[]]" >

    <div class="featureBox group">

      <% @features.each do |feat| %>
      <label for="<%= feat.feature_name %>">
      <div class="featureCheck">
          <input type="checkbox" name="search_params[features][]" id="<%= feat.feature_name %>" value="<%=feat.id %>" <%= "checked" if @current_features.include? feat.id.to_s %>> <%= feat.feature_name %>
      </div>
      <% end %>

    </div>
  </label>

</form>


<%= javascript_include_tag "map.js" %>

app/views/offices/_form.html.erb
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" /></div>

  <div class="field">
    <label for="office_title">Title</label><br />
    <input id="office_title" name="office[title]" size="30" type="text" value="<%= @office.title %>"/>
  </div>
  <div class="field">
    <label for="office_description">Description</label><br />
    <textarea cols="40" id="office_description" name="office[description]" rows="20" value="<%= @office.description %>">
</textarea>
  </div>
  <div class="field">
    <label>
      Image: <input type="file" name=photos[picture]>
    </label>
  </div>
  <div class="field">
    <label for="office_addr1">Addr1</label><br />
    <input id="office_addr1" name="office[addr1]" size="30" type="text" value="<%= @office.addr1 %>"/>
  </div>
  <div class="field">
    <label for="office_addr2">Addr2</label><br />
    <input id="office_addr2" name="office[addr2]" size="30" type="text" value="<%= @office.addr2 %>"/>
  </div>
  <div class="field">
    <label for="office_city">City</label><br />
    <input id="office_city" name="office[city]" size="30" type="text" value="<%= @office.city %>"/>
  </div>
  <div class="field">
    <label for="office_state">State</label><br />
    <input id="office_state" name="office[state]" size="30" type="text" value="<%= @office.state %>"/>
  </div>
  <div class="field">
    <label for="office_zip">Zip</label><br />
    <input id="office_zip" name="office[zip]" size="30" type="text" value="<%= @office.zip %>"/>
  </div>
  <div class="field">
    <label for="office_size">Size</label><br />
    <input id="office_size" name="office[size]" type="number" value="<%= @office.size %>"/>
  </div>
  <div class="field">
    <label for="office_occupancy">Occupancy</label><br />
    <input id="office_occupancy" name="office[occupancy]" type="number" value="<%= @office.occupancy %>"/>
  </div>
  <div class="field">
    <label for="office_price">Price</label><br />
    <input id="office_price" name="office[price]" type="number" value="<%= @office.price %>"/>
  </div>
  <div class="field">
    <label for="office_arrangement">Arrangement</label><br />
    <input id="office_arrangement" name="office[arrangement]" size="30" type="text" value="<%= @office.arrangement %>"/>
  </div>
  <div>
    <p>Features</p>
      <input type="hidden" name="features[]"></input>
      <div class="featureBox group">
        <% @features.each do |feat| %>
        <div class="featureCheck">
          <label>
            <input type="checkbox" name="features[]" id="<%= feat.feature_name %>" value="<%=feat.id %>" <%= "checked" if @current_features.include? feat.id %>><%= feat.feature_name %> </input>
          </label>
        </div>
        <% end %>
      </div>
  </div>




  <% @availabilities.each_with_index do |a, aindex| %>
  <h3>Availability <%= aindex+1 %></h3>
    <% if a.id != nil %>
      <input type="hidden" name="availabilities[<%= aindex %>][id]" value="<%= a.id %>" >
    <% end %>
    <div class="field">
      <label for="availability_start_date">Start date</label><br />
      <input type="date" name="availabilities[<%= aindex %>][start_date]" value="<%= a.start_date %>">

    </div>
    <div class="field">
      <label for="availability_end_date">End date</label><br />
      <input type="date" name="availabilities[<%= aindex %>][end_date]" value="<%= a.end_date %>">
    </div>
  <% end %>
  <p>
    Leave an availability blank and it won't be added.
  </p>

app/views/offices/_tile.html.erb
<div class="listing-tile group">
  <div class="search-image">

    <% office_image = office.photos[0].picture.url(:search) if  office.photos[0] %>
    <% if office_image != nil %>
      <%= link_to (image_tag  office_image), office%>
    <% else %>
      <%= link_to (image_tag "default-image.gif"), office %>
    <% end %>
  </div>
  <div class="search-footer group">
    <p>
      <%= office.title %>
    </p>
    <p>
      $<%= office.price %>
    </p>

  </div>
</div>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<form accept-charset="UTF-8" action="<%= office_url(@office.id) %>" class="edit_office" method="post" enctype="multipart/form-data"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="put" />
<%= render 'form' %>

  <div class="actions">
    <input name="commit" type="submit" value="Edit Office" />
  </div>

</form>


<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/find.html.erb
<!-- <h1>Listing offices</h1> -->

<section class="filter-controls">
Filters!
  <%= render "filter" %>
  <hr>
</section>

<div class="tile-field group">
<% @offices.each do |office| %>
  <%= render "tile", office: office %>
<% end %>
</div>


<script>

</script>

app/views/offices/index.html.erb
<!-- <h1>Listing offices</h1> -->

<section class="filter-controls group">
  Filters!
  <%= render "filter" %>
  <hr>
</section>

<div class="tile-field group">
<% @offices.each do |office| %>
  <div class="listing-tile group">
    <div class="search-image">

      <% office_image = office.photos[0].picture.url(:search) if  office.photos[0] %>
      <% if office_image != nil %>
        <%= link_to (image_tag  office_image), office%>
      <% else %>
        <%= link_to (image_tag "default-image.gif"), office %>
      <% end %>
    </div>
    <div class="search-footer group">
      <p>
        <%= office.title %>
      </p>
      <p>
        $<%= office.price %>
      </p>

    </div>
  </div>
<% end %>
</div>

app/views/offices/new.html.erb
<h1>New office</h1>

<form accept-charset="UTF-8" action="/offices" class="new_office" id="new_office" method="post" enctype="multipart/form-data"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" />

<%= render 'form' %>


  <div class="actions">
    <input name="commit" type="submit" value="Create Office" />
  </div>

</form>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<div class="listing-header group">
  <p id="notice"><%= notice %></p>
  <div class="listing-title group">
    <div class="address-block group">
      <b>
      <%= @office.title %>
      </b>
      <p>
        <%= @office.addr1 %>
      </p>

      <% if @office.addr2 %>
      <p>
        <%= @office.addr2 %>
      </p>
      <% end %>

      <p>
        <%= @office.city %>
      </p>
      <p>
        <%= @office.state %>
      </p>
      <p>
        <%= @office.zip %>
      </p>
    </div>
    <% if current_user && !Favorite.find_by_user_id_and_office_id(current_user.id, @office.id)%>

      <%= button_to "Track this Listing", {controller: "favorites", action: "create", office_id: @office.id}, {class: "track-button group"} %>

    <% end %>

  </div>


  <section class="primary-image group">
    <% if @photos %>
      <%= image_tag @photos.picture.url(:profile) %>
    <% else %>
      <%= image_tag "default-image.gif" %>
    <% end %>
  </section>
  <section class="office-map group">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@office.latitude}%2C#{@office.longitude}" %>
  </section>
</div>

<div class="listing-body group">

  <p>
    <b>Description:</b>
    <%= @office.description %>
  </p>

  <p>
    <b>Size:</b>
    <%= @office.size %>
  </p>

  <p>
    <b>Owner:</b>
    <%= @office.owner_id %>
  </p>

  <p>
    <b>Available:</b>
    <%= @office.available %>
  </p>

  <p>
    <b>Occupancy:</b>
    <%= @office.occupancy %>
  </p>

  <p>
    <b>Price:</b>
    <%= @office.price %>
  </p>

  <p>
    <b>Arrangement:</b>
    <%= @office.arrangement %>
  </p>

  <b>Features</b>
  <div class="featureBox group">

    <% @features.each do |feat| %>
    <div class="featureCheck">
      <%= (button_to "",
         Featuring.find_by_office_id_and_feature_id(@office.id, feat.id),
         method: :delete, class: "killFeature delete-button",
         data: {confirm: "Are you sure?"} ) if (logged_in? && current_user.id == @office.owner_id)%>

      <label>
        <%= feat.feature_name %>
      </label>
    </div>
    <% end %>

  </div>


  <% unless @availabilities.empty? || (logged_in? && deal_open?(@office.id)) %>
  <%= button_to "Arrange a Rental!", {controller: "deals", action: "create", office_id: @office.id }, {office_id: @office.id, class: "rental-button"} if (logged_in? && current_user.id != @office.owner_id)  %>
    <% @availabilities.each_with_index do |availability, ai| %>
      <p>
        <b>Availability <%= ai+1 %>:</b>
        <%= availability.start_date %> to <%= availability.end_date %> <%= link_to "Delete!", availability, method: :delete, data: {confirm: "Are you sure?"} if (logged_in? && current_user.id == @office.owner_id) %>
      </p>
    <% end %>
  <% end %>

  <%= link_to "Delete Listing!", @office, method: :delete, data: {confirm: "Are you sure?"} if (logged_in? && current_user.id == @office.owner_id) %>

  <%= link_to 'Edit', edit_office_path(@office) %> |
  <%= link_to 'Back', offices_path %>

</div>