config/routes.rb
Wanderdesk::Application.routes.draw do

  resources :offices
  match 'offices/find' => 'offices#find'
  resources :users
  resources :deals do
    resources :messages
  end
  resource :session
  resources :favorites, only: [:create, :index]
  resources :availabilities
  resources :features
  resources :featurings
  resources :tags

  root to: "offices#index"

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :office_id, :user_id

  belongs_to(:user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  belongs_to(:office,
  class_name: "Office",
  foreign_key: :office_id,
  primary_key: :id
  )

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @offices = (current_user).favorite_offices
  end


  def create
    @office = Office.find(params[:office_id])
    @fav = Favorite.new
    @fav.office_id = params[:office_id]
    @fav.user_id = current_user.id
    if @fav.save
      redirect_to @office, method: :get
    else
      flash[:errors] = @office.errors.full_messages
      render @office
    end
  end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<h1>Favorite offices</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Addr1</th>
    <th>City</th>
    <th>Available</th>
    <th>Occupancy</th>
    <th>Price</th>
    <th>Arrangement</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offices.each do |office| %>
  <tr>
    <td><%= link_to office.title, office %></td>
    <td><%= office.addr1 %></td>
    <td><%= office.city %></td>
    <td><%= office.available %></td>
    <td><%= office.occupancy %></td>
    <td><%= office.price %></td>
    <td><%= office.arrangement %></td>
    <% if office.owner_id == current_user.id  %>
      <td><%= link_to 'Edit', edit_office_path(office) %></td>
      <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Office', new_office_path %>