config/routes.rb
Wanderdesk::Application.routes.draw do

  resources :offices
  match 'offices/find' => 'offices#find'
  resources :users
  resources :deals do
    resources :messages
  end
  resource :session
  resources :favorites, only: [:create, :index]
  resources :availabilities
  resources :features
  resources :featurings
  resources :tags

  root to: "offices#index"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :end_date, :office_id, :owner_approval, :owner_id, :price, :renter_approval, :renter_id, :start_date

  belongs_to(:owner,
  class_name: "User",
  foreign_key: :owner_id,
  primary_key: :id
  )

  belongs_to(:renter,
  class_name: "User",
  foreign_key: :renter_id,
  primary_key: :id
  )

  belongs_to(:office,
  class_name: "Office",
  foreign_key: :office_id,
  primary_key: :id
  )

  has_many(:messages,
  class_name: "Message",
  foreign_key: :deal_id,
  primary_key: :id,
  dependent: :destroy
  )


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    @deals = current_user.deals
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def new
    # Not needed, should only derive from listings.
  end

  def create
    @deal = Deal.new(params[:deal])
    @deal.office_id = params[:office_id]
    @office = Office.find(params[:office_id])

    @deal.renter_id = current_user.id
    @deal.owner_id = @office.owner_id
    @deal.price = @office.price
    @deal.owner_approval = false
    @deal.renter_approval = false
    availability = @office.availabilities.sort_by{|o| o.start_date }.first || nil
    @deal.start_date = availability.start_date || nil
    @deal.end_date = availability.end_date || nil

    if @deal.save
      redirect_to edit_deal_url(@deal.id)
    else
      flash[:errors] = @deal.errors.full_messages
      render :new
    end
  end

  def edit
    @deal = Deal.find(params[:id])
    @office = Office.find(@deal.office_id)
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.owner_id == current_user.id
      @deal.owner_approval = false unless params[:deal][:owner_approval]
    else
      @deal.renter_approval = false unless params[:deal][:renter_approval]
    end
    @deal.update_attributes(params[:deal])
    @deal.save
    redirect_to deals_url
  end

  def destroy
  end


end

app/helpers/deals_helper.rb
module DealsHelper

  def other_party_deal(deal)
    # fail
    return deal.owner_id if deal.owner_id == current_user.id
    return deal.renter_id
  end

end

app/views/deals/edit.html.erb
  <!-- attr_accessible :end_date, :office_id, :owner_approval, :owner_id, :price, :renter_approval, :renter_id, :start_date -->
  <% owner = (current_user.id == @deal.owner_id) %>
  <% other_approved = owner ? @deal.renter_approval : @deal.owner_approval %>
  <% current_user_approved = owner ? @deal.owner_approval : @deal.renter_approval %>
  <div class="negotiation group">
  <form action="<%= deal_url(@deal.id) %>" method="post">
    <%= auth %>
    <input type="hidden" name="_method" value="put">
    <p>
      <label>
        Owner: <%= @deal.owner.name %>
      </label>
    </p>
    <p>
      <label>
        Renter: <%= @deal.renter.name %>
      </label>
    </p>
    <p>
      <label>
        Office: <%= @office.title %>
      </label>
    </p>
    <p>
      <%= @office.description %>
    </p>
    <p>
      <label>
        Approve?

        <input type="checkbox" name="<%= owner ? "deal[owner_approval]" : "deal[renter_approval]"%>" <%= "checked" if current_user_approved %>>
      </label>
      <p><b>
        <%= owner ? "Renter " : "Owner "%> has <%= other_approved ? " approved this deal." : "not approved this deal." %>
      </b></p>
    </p>
    <p>
      <label>Price
        <input type="integer" name="deal[price]" <%= "value=#{@deal.price}" if @deal.price %> >
      </label>
    </p>
    <p>

      <label>Start Date
        <input type="date" name="deal[start_date]" <%= "value=#{@deal.start_date}" if @deal.start_date %>>
      </label>
    </p>
    <p>
      <label>End Date
        <input type="date" name="deal[end_date]" <%= "value=#{@deal.end_date}" if @deal.end_date %>>
      </label>
    </p>
    <input type="submit" value="Update Deal!">

  </form>
</div>
<div class="conversation group">
  <div class="message-box group">
    <form action="<%= deal_messages_url(@deal) %>" method="post">
      <%= auth %>
      <input type="submit" value="Send Message" class="send-message">
      <textarea name="message[message_body]" class="message-field"></textarea>
    </form>
  </div>
  <div class="conversation-history group">
    <% @deal.messages.each do |message| %>
    <div class="individual-message <%= message.sending_party %>"><%= message.message_body %></div>
    <% end %>
  </div>
</div>

app/views/deals/index.html.erb
<h1>Your Deals</h1>
<ul>
<% @deals.each do |deal| %>
<li>
  <% next if deal.office == nil %>
  <%= link_to deal.office.title, edit_deal_url(deal) %>
</li>
<% end %>
</ul>